name: Unified Deploy to Docker and Non-Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Docker
      run: |
        start_time=$(date +%s)
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.DOCKER_HOST }} "
        cd /home/ubuntu/aws_test_0529
        git pull
        sudo docker-compose down
        sudo docker-compose up -d --build
        "
        end_time=$(date +%s)
        echo "Docker Deployment took $((end_time - start_time)) seconds"


    - name: Deploy to None Docker
      run: |
        start_time=$(date +%s)
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.DOCKER_HOST }} "
        cd /home/ubuntu/aws_test_0529
        git pull
        sudo docker-compose down
        sudo docker-compose up -d --build
        "
        end_time=$(date +%s)
        echo "Docker Deployment took $((end_time - start_time)) seconds"


    



    
